III-4814 embed UiTPASPrices
cultuurnet/udb3-search-service pull request #215
Opened 2022-07-28 08:48 UTC by JonasVHG

### Added
 
- Created an UiTPASPricesTransformer
- Added a parameter to embed UiTPAS Prices
 
---

Ticket: https://jira.uitdatabank.be/browse/III-4814

2022-07-29 14:20 UTC, bertramakers approved these changes

2022-07-29 14:21 UTC, bertramakers commented
Sorry I accidentally approved this instead of another PR, will review this soon!

2022-07-29 14:23 UTC, bertramakers commented on src/ElasticSearch/JsonDocument/UiTPASPricesTransformer.php
> +            if ($priceInfo['category'] !== 'uitpas') {
This should also check that `$priceInfo` is an array and has a `category` key

2022-07-29 14:26 UTC, bertramakers commented on src/ElasticSearch/JsonDocument/UiTPASPricesTransformer.php
> +        if (!isset($from['priceInfo']) || !is_array($from['priceInfo'])) {
This will always resolve to `true` because `$from` is always the original JSON that is returned by Elasticsearch in this case. The `$draft` is the array that contains the JSON that will be returned as results, and what will contain `priceInfo`.

2022-07-29 14:28 UTC, bertramakers requested changes
(See other comments)

2022-08-01 09:23 UTC, bertramakers approved these changes
Great work, easy to review as well with the small commits! 👌

2022-08-01 11:36 UTC, LucWollants approved these changes
Looks good.

2022-08-01 12:20 UTC, merged