III-6220 Refactor ManagementToken as preparation for Keycloak
cultuurnet/udb3-search-service pull request #290
Opened 2024-06-17 14:20 UTC by LucWollants

### Changed
- Refactor `Auth0` specific management code to interfaces so they can be implemented with a Keycloak flavor
- The `JsonDocumentFetcher` only needs a token
- The `AuthenticateRequest` also needs to make a management call

### Note
- The behavior should be the same as before. But with these changes and interfaces, it is possible to implement a Keycloak flavor
 
---

Ticket: https://jira.uitdatabank.be/browse/III-6220

2024-06-17 14:45 UTC, grubolsch requested changes

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +final class Auth0ManagementTokenGenerator implements ManagementTokenGenerator, LoggerAwareInterface
Is there any way to set the Logger? It should be an optional dependency?

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +    public function newToken(): ManagementToken
I personally like the name functions that make api calls with the prefix "fetch". This fetches a different token each time you call it, it does not return the same "new token".
So I would rename it to fetchNewToken()

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/ManagementToken/ManagementTokenProvider.php
> +        if ($token === null || $this->expiresWithin($token, '+5 minutes')) {
Move string to a constant

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/ManagementToken/ManagementTokenProvider.php
> +    private function expiresWithin(ManagementToken $token, string $offset): bool
offset will always be +5 minutes so remove param and use constant/string hardcoded?

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/ManagementToken/ManagementTokenFileRepository.php
> +        return new ManagementToken(
Should we check if the fields `token`, `issuesAt` & `expiresIn` are returned? If not return `NULL`?

2024-06-17 14:45 UTC, grubolsch commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +        $res = Json::decodeAssociatively($response->getBody()->getContents());
I think this is a difference in style, but I would check if the fields `access_token` & `expires_in` are returned.
And check if JSON throws a JsonException, in either of these cases I would throw a ConnectException.

2024-06-18 07:28 UTC, LucWollants commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +final class Auth0ManagementTokenGenerator implements ManagementTokenGenerator, LoggerAwareInterface
It works with the `LoggerAwareTrait` trait, but it was never set before. We could create a follow-up ticket to change this behavior.

2024-06-18 07:30 UTC, LucWollants commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +    public function newToken(): ManagementToken
The method comes from the interface `ManagementTokenGenerator`, this interface does not imply that the token is created through an HTTP request, the token could also be created locally. Maybe `generate` is a better name that matches the `ManagementTokenGenerator` interface better?

2024-06-18 07:32 UTC, LucWollants commented on src/Http/Authentication/ManagementToken/ManagementTokenProvider.php
> +    private function expiresWithin(ManagementToken $token, string $offset): bool
I changed the method to `isExpired` and the offset is internal, so no longer need for a constant

2024-06-18 07:36 UTC, LucWollants commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +        $res = Json::decodeAssociatively($response->getBody()->getContents());
That means there was something wrong with the `set` method and we would never notice this. If we overlook that and always return `null` from the cache we will always create a new token. So I would prefer a hard crash that allows us to fix the issue.

2024-06-19 09:05 UTC, LucWollants commented on src/Http/Authentication/ManagementToken/ManagementTokenFileRepository.php
> +        return new ManagementToken(
That means there was something wrong with the set method and we would never notice this. If we overlook that and always return null from the cache we will always create a new token. So I would prefer a hard crash that allows us to fix the issue.

2024-06-19 10:14 UTC, grubolsch commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +    public function newToken(): ManagementToken
I can live with generate :-)

2024-06-19 10:14 UTC, grubolsch commented on src/Http/Authentication/ManagementToken/ManagementTokenFileRepository.php
> +        return new ManagementToken(
okay

2024-06-19 10:14 UTC, grubolsch approved these changes

2024-06-19 11:14 UTC, LucWollants commented on src/Http/Authentication/Auth0/Auth0ManagementTokenGenerator.php
> +    public function newToken(): ManagementToken
I became a little more complex. Turns out we need to create a management token to validate an incoming access token an we need to create a login token to make authenticated requests to UDB3. So in the follow-up pull request the interface changed again 😅

2024-06-19 14:26 UTC, merged